version: 2
groups:
  code-review:
    author_approval:
      required: true
    approve_by_comment:
      enabled: false
    required: 1
    reset_on_push:
      enabled: true
    users:
    - gdemarcsek
    - kepten
